.nh
.TH "REFIND-BTRFS-SNAPSHOTS" "1" "May 2026" "refind-btrfs-snapshots" "refind-btrfs-snapshots Manual"

.SH NAME
refind-btrfs-snapshots-completion-zsh - Generate the autocompletion script for zsh


.SH SYNOPSIS
\fBrefind-btrfs-snapshots completion zsh [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for the zsh shell.

.PP
If shell completion is not already enabled in your environment you will need
to enable it.  You can execute the following once:

.EX
echo "autoload -U compinit; compinit" >> ~/.zshrc
.EE

.PP
To load completions in your current shell session:

.EX
source <(refind-btrfs-snapshots completion zsh)
.EE

.PP
To load completions for every new session, execute once:

.SS Linux:
.EX
refind-btrfs-snapshots completion zsh > "${fpath[1]}/_refind-btrfs-snapshots"
.EE

.SS macOS:
.EX
refind-btrfs-snapshots completion zsh > $(brew --prefix)/share/zsh/site-functions/_refind-btrfs-snapshots
.EE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for zsh

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is /etc/refind-btrfs-snapshots.yaml)

.PP
\fB--local-time\fP[=false]
	Display times in local time instead of UTC

.PP
\fB--log-level\fP="info"
	log level (trace, debug, info, warn, error, fatal, panic)


.SH SEE ALSO
\fBrefind-btrfs-snapshots-completion(1)\fP


.SH HISTORY
28-May-2026 Auto generated by spf13/cobra
