.nh
.TH "REFIND-BTRFS-SNAPSHOTS" "1" "May 2026" "refind-btrfs-snapshots" "refind-btrfs-snapshots Manual"

.SH NAME
refind-btrfs-snapshots-generate - Generate rEFInd boot entries for btrfs snapshots


.SH SYNOPSIS
\fBrefind-btrfs-snapshots generate [flags]\fP


.SH DESCRIPTION
Generate rEFInd boot configuration files for btrfs snapshots.

.PP
Automatically detects snapshots, updates fstab files, and creates boot entries.
Prefers refind_linux.conf updates but can generate include files when needed.


.SH OPTIONS
\fB--config-path\fP=""
	Path to rEFInd main config file

.PP
\fB-n\fP, \fB--count\fP=0
	Number of snapshots to include (0 = all snapshots)

.PP
\fB--dry-run\fP[=false]
	Show what would be done without making changes

.PP
\fB-e\fP, \fB--esp-path\fP=""
	Path to ESP mount point

.PP
\fB--force\fP[=false]
	Force generation even if booted from snapshot

.PP
\fB-g\fP, \fB--generate-include\fP[=false]
	Force generation of refind-btrfs-snapshots.conf for inclusion into refind.conf

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for generate

.PP
\fB-y\fP, \fB--yes\fP[=false]
	Automatically approve all changes without prompting


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is /etc/refind-btrfs-snapshots.yaml)

.PP
\fB--local-time\fP[=false]
	Display times in local time instead of UTC

.PP
\fB--log-level\fP="info"
	log level (trace, debug, info, warn, error, fatal, panic)


.SH SEE ALSO
\fBrefind-btrfs-snapshots(1)\fP


.SH HISTORY
28-May-2026 Auto generated by spf13/cobra
